# Generated by Django 4.1.5 on 2023-02-02 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 2, 2, 7, 11, 19, 768957, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
