# Generated by Django 4.1.5 on 2023-02-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_notice_result_file_notice_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
