# Generated by Django 4.1.5 on 2023-02-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_results_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='unread_links',
            field=models.BigIntegerField(default=0),
        ),
    ]
